Category 1 - M SubCategory 1 - M Product

Vendor 1 - M Product

Product 1 - M InventorySnapshot

Product 1 - M WeeklySales

ImportBatch 1 - M WeeklySales

ImportBatch 1 - M InventorySnapshot

Role 1 - M User

Table Category {
    CategoryId int [pk, increment]
    
}